// > grep ' extends GroovyParserRuleContext' src/antlr4/GroovyParser.ts | \
//     sed -e 's/^export class \(.*\) extends GroovyParserRuleContext {$/| GroovyParser.\1/g'

import * as GroovyParser from './antlr4/GroovyParser';

export type Context =
  | GroovyParser.CompilationUnitContext
  | GroovyParser.StatementsContext
  | GroovyParser.PackageDeclarationContext
  | GroovyParser.ImportDeclarationContext
  | GroovyParser.TypeDeclarationContext
  | GroovyParser.ModifierContext
  | GroovyParser.ModifiersOptContext
  | GroovyParser.ModifiersContext
  | GroovyParser.ClassOrInterfaceModifiersOptContext
  | GroovyParser.ClassOrInterfaceModifiersContext
  | GroovyParser.ClassOrInterfaceModifierContext
  | GroovyParser.VariableModifierContext
  | GroovyParser.VariableModifiersOptContext
  | GroovyParser.VariableModifiersContext
  | GroovyParser.TypeParametersContext
  | GroovyParser.TypeParameterContext
  | GroovyParser.TypeBoundContext
  | GroovyParser.TypeListContext
  | GroovyParser.ClassDeclarationContext
  | GroovyParser.ClassBodyContext
  | GroovyParser.EnumConstantsContext
  | GroovyParser.EnumConstantContext
  | GroovyParser.ClassBodyDeclarationContext
  | GroovyParser.MemberDeclarationContext
  | GroovyParser.MethodDeclarationContext
  | GroovyParser.MethodNameContext
  | GroovyParser.ReturnTypeContext
  | GroovyParser.FieldDeclarationContext
  | GroovyParser.VariableDeclaratorsContext
  | GroovyParser.VariableDeclaratorContext
  | GroovyParser.VariableDeclaratorIdContext
  | GroovyParser.VariableInitializerContext
  | GroovyParser.VariableInitializersContext
  | GroovyParser.DimsContext
  | GroovyParser.DimsOptContext
  | GroovyParser.TypeContext
  | GroovyParser.ClassOrInterfaceTypeContext
  | GroovyParser.PrimitiveTypeContext
  | GroovyParser.TypeArgumentsContext
  | GroovyParser.TypeArgumentContext
  | GroovyParser.AnnotatedQualifiedClassNameContext
  | GroovyParser.QualifiedClassNameListContext
  | GroovyParser.FormalParametersContext
  | GroovyParser.FormalParameterListContext
  | GroovyParser.ThisFormalParameterContext
  | GroovyParser.FormalParameterContext
  | GroovyParser.MethodBodyContext
  | GroovyParser.QualifiedNameContext
  | GroovyParser.QualifiedNameElementContext
  | GroovyParser.QualifiedNameElementsContext
  | GroovyParser.QualifiedClassNameContext
  | GroovyParser.QualifiedStandardClassNameContext
  | GroovyParser.LiteralContext
  | GroovyParser.GstringContext
  | GroovyParser.GstringValueContext
  | GroovyParser.GstringPathContext
  | GroovyParser.StandardLambdaExpressionContext
  | GroovyParser.StandardLambdaParametersContext
  | GroovyParser.LambdaBodyContext
  | GroovyParser.ClosureContext
  | GroovyParser.ClosureOrLambdaExpressionContext
  | GroovyParser.BlockStatementsOptContext
  | GroovyParser.BlockStatementsContext
  | GroovyParser.AnnotationsOptContext
  | GroovyParser.AnnotationContext
  | GroovyParser.ElementValuesContext
  | GroovyParser.AnnotationNameContext
  | GroovyParser.ElementValuePairsContext
  | GroovyParser.ElementValuePairContext
  | GroovyParser.ElementValuePairNameContext
  | GroovyParser.ElementValueContext
  | GroovyParser.ElementValueArrayInitializerContext
  | GroovyParser.BlockContext
  | GroovyParser.BlockStatementContext
  | GroovyParser.LocalVariableDeclarationContext
  | GroovyParser.ClassifiedModifiersContext
  | GroovyParser.VariableDeclarationContext
  | GroovyParser.TypeNamePairsContext
  | GroovyParser.TypeNamePairContext
  | GroovyParser.VariableNamesContext
  | GroovyParser.ConditionalStatementContext
  | GroovyParser.IfElseStatementContext
  | GroovyParser.SwitchStatementContext
  | GroovyParser.LoopStatementContext
  | GroovyParser.ContinueStatementContext
  | GroovyParser.BreakStatementContext
  | GroovyParser.TryCatchStatementContext
  | GroovyParser.AssertStatementContext
  | GroovyParser.StatementContext
  | GroovyParser.CatchClauseContext
  | GroovyParser.CatchTypeContext
  | GroovyParser.FinallyBlockContext
  | GroovyParser.ResourcesContext
  | GroovyParser.ResourceListContext
  | GroovyParser.ResourceContext
  | GroovyParser.SwitchBlockStatementGroupContext
  | GroovyParser.SwitchLabelContext
  | GroovyParser.ForControlContext
  | GroovyParser.EnhancedForControlContext
  | GroovyParser.ClassicalForControlContext
  | GroovyParser.ForInitContext
  | GroovyParser.ForUpdateContext
  | GroovyParser.CastParExpressionContext
  | GroovyParser.ParExpressionContext
  | GroovyParser.ExpressionInParContext
  | GroovyParser.ExpressionListContext
  | GroovyParser.ExpressionListElementContext
  | GroovyParser.EnhancedStatementExpressionContext
  | GroovyParser.StatementExpressionContext
  | GroovyParser.PostfixExpressionContext
  | GroovyParser.ExpressionContext
  | GroovyParser.CommandExpressionContext
  | GroovyParser.CommandArgumentContext
  | GroovyParser.PathExpressionContext
  | GroovyParser.PathElementContext
  | GroovyParser.NamePartContext
  | GroovyParser.DynamicMemberNameContext
  | GroovyParser.IndexPropertyArgsContext
  | GroovyParser.NamedPropertyArgsContext
  | GroovyParser.PrimaryContext
  | GroovyParser.ListContext
  | GroovyParser.MapContext
  | GroovyParser.MapEntryListContext
  | GroovyParser.MapEntryContext
  | GroovyParser.MapEntryLabelContext
  | GroovyParser.CreatorContext
  | GroovyParser.ArrayInitializerContext
  | GroovyParser.AnonymousInnerClassDeclarationContext
  | GroovyParser.CreatedNameContext
  | GroovyParser.NonWildcardTypeArgumentsContext
  | GroovyParser.TypeArgumentsOrDiamondContext
  | GroovyParser.ArgumentsContext
  | GroovyParser.EnhancedArgumentListContext
  | GroovyParser.EnhancedArgumentListElementContext
  | GroovyParser.StringLiteralContext
  | GroovyParser.ClassNameContext
  | GroovyParser.IdentifierContext
  | GroovyParser.BuiltInTypeContext
  | GroovyParser.KeywordsContext
  | GroovyParser.RparenContext
  | GroovyParser.NlsContext
  | GroovyParser.SepContext;
